services:

  backend:
    build:
      context: ./backend

    container_name: securedocs-backend

    depends_on:
      - postgres
      - redis
      - fernet-rest-service

    expose:
      - "3000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend/uploads:/app/uploads

    restart: unless-stopped

  fernet-rest-service:
    build:
      context: ./fernet-file-service/fernet-rest-service

    container_name: securedocs-fernet

    env_file:
      - ./fernet-file-service/fernet-rest-service/.env

    expose:
      - "4000"

    restart: unless-stopped

  nginx:
    image: nginx:alpine

    container_name: securedocs-nginx

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend

    restart: unless-stopped

  postgres:
    image: postgres:17-alpine

    container_name: securedocs-postgres

    environment:
      POSTGRES_DB: securedocs
      POSTGRES_USER: securedocs_admin
      POSTGRES_PASSWORD: securedocs_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7-alpine

    container_name: securedocs-redis

    restart: unless-stopped

  authentik-server:
    image: ghcr.io/goauthentik/server:latest

    container_name: securedocs-authentik-server

    command: server

    env_file:
      - ./docker/authentik/.env

    depends_on:
      - postgres
      - redis

    ports:
      - "9000:9000"

    restart: unless-stopped

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest

    container_name: securedocs-authentik-worker

    command: worker

    env_file:
      - ./docker/authentik/.env

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

volumes:
  postgres_data: